name: CI - Build & Test Spring Boot Backend

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build app
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > backend/.env
          echo "KAFKA_SERVERS=${{ secrets.KAFKA_SERVERS }}" >> backend/.env
          echo "KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME }}" >> backend/.env
          echo "KAFKA_PASSWORD=${{ secrets.KAFKA_PASSWORD }}" >> backend/.env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> backend/.env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> backend/.env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> backend/.env
          echo "GOOGLE_APP_USERNAME=${{ secrets.GOOGLE_APP_USERNAME }}" >> backend/.env
          echo "GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}" >> backend/.env
          echo "KAFKA_SERVER=${{ secrets.KAFKA_SERVER }}" >> backend/.env
          echo "WEATHER_APP_KEY=${{ secrets.WEATHER_APP_KEY }}" >> backend/.env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> backend/.env
          echo "DATABASE_ACTIVE=${{ secrets.DATABASE_ACTIVE }}" >> backend/.env
      

      - name: Copy JAR and .env to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            backend/target/*.jar
            backend/.env
          target: "~/app"

      - name: SSH and deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f 'java -jar' || echo "Nothing to kill"
            mkdir -p ~/app/target
            mv ~/app/*.jar ~/app/target/app.jar
            mv ~/app/.env ~/app/target/.env
            cd ~/app/target
            nohup java -jar app.jar > app.log 2>&1 &

