name: CI - Build & Test Spring Boot Backend

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Check Java version
        run: java -version

      - name: Check Maven version
        run: mvn -version

      - name: Create .env file
        working-directory: backend
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "KAFKA_SERVERS=${{ secrets.KAFKA_SERVERS }}" >> .env
          echo "KAFKA_USERNAME=${{ secrets.KAFKA_USERNAME }}" >> .env
          echo "KAFKA_PASSWORD=${{ secrets.KAFKA_PASSWORD }}" >> .env
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env
          echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env
          echo "GOOGLE_APP_USERNAME=${{ secrets.GOOGLE_APP_USERNAME }}" >> .env
          echo "GOOGLE_APP_PASSWORD=${{ secrets.GOOGLE_APP_PASSWORD }}" >> .env
          echo "KAFKA_SERVER=${{ secrets.KAFKA_SERVER }}" >> .env
          echo "WEATHER_APP_KEY=${{ secrets.WEATHER_APP_KEY }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_ACTIVE=${{ secrets.DATABASE_ACTIVE }}" >> .env

      - name: Build with Maven
        working-directory: backend
        run: mvn clean package -DskipTests

      - name: Deploy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/target/DailySync-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/dailysync/"

      - name: Upload start.sh to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "backend/start.sh"
          target: "/home/ec2-user/dailysync/"
          strip_components: 1

      - name: Verify Deployment Directory and Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Checking directory contents..."
            ls -lh /home/ec2-user/dailysync/
            echo "Checking Java version on EC2..."
            java -version

      - name: Restart Spring Boot App on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            chmod +x /home/ec2-user/dailysync/start.sh
            bash /home/ec2-user/dailysync/start.sh
